---
- hosts: aws
  remote_user: ec2-user
  become: true

  tasks:
  - name: Create Ansible drop-point
    file: path=/root/git/ansible state=directory mode=0700

  - name: Copy iptables template to host
    copy:
      src: /srv/ansible/iptables_base.save 
      dest: /root/ansible/iptables_base.save
      force: yes

  - name: Import IPTables file
    shell: "/usr/sbin/iptables-restore < /root/ansible/iptables_base.save"
    args:
      executable: /bin/bash

  - name: Savee using service iptables save
    shell: /usr/sbin/service iptables save
    args:
      executable: /bin/bash

