---
- name: Copy epel package
  copy: 
    src: files/epel-release-latest-7.noarch.rpm
    dest: /root/ansible/epel-release-latest-7.noarch.rpm
    force: yes

- name: Install EPEL RPM
  yum: 
    name: /root/ansible/epel-release-latest-7.noarch.rpm 
    state: present

- name: Update EPEL package
  yum:
    name: epel-release
    state: latest

