- name: Install base package set 
  yum:
    state: present
    name: "{{ item }}"
  with_items:
  - vim
  - git 
  - mutt
  - iptables-services
  - mailx
  - mlocate

- name: Prevent saving of sent message (can get bloated)
  shell: "echo set copy = no > /etc/Muttrc.local"
